// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo1hRjrHX3A6N-lKh7RGcMwoz2DRI89Y0',
    appId: '1:1043050659647:web:0c13dc309091fa3d375d8a',
    messagingSenderId: '1043050659647',
    projectId: 'testtung-4934e',
    authDomain: 'testtung-4934e.firebaseapp.com',
    storageBucket: 'testtung-4934e.firebasestorage.app',
    measurementId: 'G-T3B4QKKVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqhhPqSQ4HNT38waex9XGLsegP-SA8dI',
    appId: '1:1043050659647:android:adb655f62b24325f375d8a',
    messagingSenderId: '1043050659647',
    projectId: 'testtung-4934e',
    storageBucket: 'testtung-4934e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiCkICcFUCr2ZRR2Lae312m8ObL2Il01k',
    appId: '1:1043050659647:ios:84e4bf2676ef29bc375d8a',
    messagingSenderId: '1043050659647',
    projectId: 'testtung-4934e',
    storageBucket: 'testtung-4934e.firebasestorage.app',
    iosBundleId: 'com.example.testungapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiCkICcFUCr2ZRR2Lae312m8ObL2Il01k',
    appId: '1:1043050659647:ios:84e4bf2676ef29bc375d8a',
    messagingSenderId: '1043050659647',
    projectId: 'testtung-4934e',
    storageBucket: 'testtung-4934e.firebasestorage.app',
    iosBundleId: 'com.example.testungapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo1hRjrHX3A6N-lKh7RGcMwoz2DRI89Y0',
    appId: '1:1043050659647:web:9a135c5768ebb3c2375d8a',
    messagingSenderId: '1043050659647',
    projectId: 'testtung-4934e',
    authDomain: 'testtung-4934e.firebaseapp.com',
    storageBucket: 'testtung-4934e.firebasestorage.app',
    measurementId: 'G-M25T41HNSH',
  );
}
